export const START_TIMER = 'START_TIMER';
export const RESET_TIMER = 'RESET_TIMER';
export const RESET_GAME_DATA = 'RESET_GAME_DATA';
export const GENERATE_ITEMS = 'GENERATE_ITEMS';
export const INCREASE_STEP_COUNTER = 'INCREASE_STEP_COUNTER';
export const CHANGE_SELECTED_ITEM_STATE = 'CHANGE_SELECTED_ITEM_STATE';
export const CHECK_ITEMS_FOR_MATCH = 'CHECK_ITEMS_FOR_MATCH';
